# Generated by Django 3.2.9 on 2021-11-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('languages', models.CharField(help_text='Languages used when developing this project', max_length=256)),
                ('technologies', models.CharField(help_text='Technologies used when developing this project', max_length=256)),
                ('description', models.CharField(help_text='Short description of project', max_length=256)),
                ('github_page', models.URLField(help_text="Link to the project's GitHub page.", max_length=256)),
            ],
        ),
    ]
