# Generated by Django 3.2.9 on 2021-11-10 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title', '-start_date')},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='Date of project completion', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of project start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', help_text='Short description of project', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_page',
            field=models.URLField(blank=True, default=None, help_text="Link to the project's GitHub page.", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.CharField(default='', help_text='Languages used when developing this project', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='', help_text='Technologies used when developing this project', max_length=256),
        ),
    ]
