# Generated by Django 3.2.9 on 2021-11-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(help_text="Applicant's street address", max_length=255)),
                ('city', models.CharField(help_text="Applicant's city of residence", max_length=64)),
                ('state', models.CharField(help_text="Applicant's state of residence", max_length=32)),
                ('zip_code', models.SmallIntegerField(help_text="Applicant's zip code")),
                ('phone_number', models.CharField(help_text='10-digit contact phone number (assumed US number)', max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(help_text='School attended', max_length=255)),
                ('degree', models.CharField(help_text='Degree obtained from education', max_length=255)),
                ('gpa', models.FloatField(help_text='GPA received during degree')),
                ('education_body', models.TextField(default='', help_text='Body of the section')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company worked at during this employment', max_length=255)),
                ('position', models.CharField(help_text='Position while employed at the company', max_length=255)),
                ('employment_body', models.TextField(default='', help_text='Body of the section')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(help_text='Title of this section (ie Experience, Organizations, etc.)', max_length=255)),
                ('section_body', models.TextField(default='', help_text='Body of the section')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of applicant', max_length=255)),
                ('contact_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.contactinfo')),
                ('education_info', models.ManyToManyField(help_text='Select education information about the applicant', related_name='_resume_resume_education_info_+', to='resume.Education')),
                ('employment_info', models.ManyToManyField(help_text='Select employment information about the applicant', related_name='_resume_resume_employment_info_+', to='resume.Employment')),
                ('other_sections', models.ManyToManyField(help_text='Select any other sections to add to this resume', related_name='_resume_resume_other_sections_+', to='resume.Section')),
            ],
        ),
    ]
