# Generated by Django 3.2.9 on 2021-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('is_chosen', '-resume_date')},
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_chosen',
            field=models.BooleanField(default=False, verbose_name='Active_Resume'),
        ),
    ]
