# Generated by Django 3.2.9 on 2021-11-04 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 4, 21, 29, 11, 617568, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
