# Generated by Django 3.2.9 on 2021-11-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='creation_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
