# Generated by Django 3.2.9 on 2021-11-09 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20211108_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='graduation_date',
            field=models.CharField(default='', help_text='Date of graduation or expected graduation', max_length=32),
        ),
        migrations.AddField(
            model_name='employment',
            name='end_date',
            field=models.CharField(default='', help_text='Ending date of employment in the given position', max_length=32),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_date',
            field=models.CharField(default='', help_text='Starting date at the given position', max_length=32),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='city',
            field=models.CharField(default='', help_text="Applicant's city of residence", max_length=64),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='state',
            field=models.CharField(default='', help_text="Applicant's state of residence", max_length=32),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='street_address',
            field=models.CharField(default='', help_text="Applicant's street address", max_length=255),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='zip_code',
            field=models.SmallIntegerField(default=0, help_text="Applicant's zip code"),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='', help_text='Degree obtained from education', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.FloatField(default=0.0, help_text='GPA received during degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(default='', help_text='School attended', max_length=255),
        ),
        migrations.AlterField(
            model_name='employment',
            name='company',
            field=models.CharField(default='', help_text='Company worked at during this employment', max_length=255),
        ),
        migrations.AlterField(
            model_name='employment',
            name='position',
            field=models.CharField(default='', help_text='Position while employed at the company', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='full_name',
            field=models.CharField(default='', help_text='Full name of applicant', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 9, 16, 49, 40, 282964, tzinfo=utc), help_text='Enter a date the resume was last applicable'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_title',
            field=models.CharField(default='', help_text='Title of this section (ie Experience, Organizations, etc.)', max_length=255),
        ),
    ]
