# Generated by Django 3.2.9 on 2021-11-09 22:02

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20211109_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(help_text='10-digit contact phone number (assumed US number)', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 9, 22, 2, 44, 754558, tzinfo=utc), help_text='Enter a date the resume was last applicable'),
        ),
    ]
