# Generated by Django 3.2.9 on 2021-11-09 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20211109_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter a date the resume was last applicable'),
        ),
    ]
