# Generated by Django 3.2.9 on 2021-11-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20211105_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ('modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'ordering': ('modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('modified_at',)},
        ),
    ]
