# Generated by Django 3.2.9 on 2021-11-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-resume_date',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('-modified_at',)},
        ),
    ]
