name: Secret Key Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: Build
            uses: docker/build-push-action@v2
            with:
              tags:
                codesmith917/django-portfolio:latest
              secrets: |
                "SECRET_KEY=${{ secrets.SECRET_KEY }}"
