name: Secret Key Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - shell: bash
          env:
            SUPER_SECRET: ${{ secrets.SuperSecret }}
          run: |
            export SECRET_KEY="$SUPER_SECRET"
